"""initial

Revision ID: 81620c9e935f
Revises: 
Create Date: 2023-05-25 13:08:07.854457

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
import auth.models

revision = '81620c9e935f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('price', sa.Numeric(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=False),
                    sa.Column('role', sa.Enum('client', 'operator', 'admin', name='userroles'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('cart',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('product_image',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('path', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('cart_item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('cart_id', sa.Integer(), nullable=True),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Numeric(), nullable=False),
                    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
                    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('order',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_dt', sa.DateTime(), nullable=True),
                    sa.Column('delivery_dt', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('address', sa.String(), nullable=True),
                    sa.Column('cart_id', sa.Integer(), nullable=True),
                    sa.Column('status', sa.Enum('created', 'delivered', 'processed', 'cancelled', name='orderstatus'),
                              nullable=False),
                    sa.Column('total_cost', sa.Numeric(), nullable=True),
                    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )

    op.bulk_insert(
        auth.models.User.__table__,
        [
            {
                'id': 1,
                'name': 'Admin',
                'username': 'admin',
                'email': 'admin@admin.com',
                'password': '$2b$12$HlXc3fXEr/UaffJ5DJF0B.qE6oXFnjEbV1zA.XDh3r24OwvTUsQBe',
                'age': 1,
                'role': auth.models.UserRoles.admin,
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('cart_item')
    op.drop_table('product_image')
    op.drop_table('cart')
    op.drop_table('user')
    op.drop_table('product')
    # ### end Alembic commands ###
